[pytest]
addopts = -s --html=reports/report.html
testpaths = test_cases
python_files = test_*.py
markers =
    sanity: sanity test cases
    regression: regression test cases
    smoke: smoke test cases